### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by reviewer99** [milaname/prj-rev-bwfs-tea-cozy#4]
### Criteria 1: HTML Structure  
* _Score Level:_ 4
* _Comment(s):_ HTML implementation enables proper use of flexbox
 
### Criteria 2: Visual Layout
* _Score Level:_ 3
* _Comment(s):_ Layout matches the design spec in all sections. -1 for having a gap between the sticky header and the top of the viewport

![Screen Shot 2019-04-20 at 10 25 26 PM](https://user-images.githubusercontent.com/46092845/56465893-11327900-63bd-11e9-8efb-4a000f6250d0.png)

 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4
* _Comment(s):_ Flexbox properties are correctly applied to flex containers and flex items throughout
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ The page includes all style and content provided in the design specification
 
### Overall Score: 15/16

Congrats on finishing the Tea Cozy project! Overall you did a decent job implementing most of the requirements for the project. Although you a syntax error present you did an excellent job improving the readability of your project by adding comments throughout. 

For the gap that was present for in the sticky header when you scroll down on the page. You can fix this by modifying the following class:

```CSS
body {
    font-family: Helvetica;
    font-size: 22px;
    color: seashell;
    background-color: black;
    opacity: 0.9;
    text-align: center;
    /** This is the additional modification needed **/
    margin-top: 0px;
}
```

By default on some browsers, the body of the document has a default margin of `8px` on all sides including the top. Usually, this doesn't make a difference in the layout of your project by in this case this extra margin was a causing a gap in the header when you scrolled the page down. 

If you'd like to expand your project a bit more consider researching the pseudo-classes [hover](https://www.w3schools.com/CSSref/sel_hover.asp), [active](https://www.w3schools.com/CSSref/sel_active.asp) and the property [transition](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions). Hover, active and the transition property are commonly used together as showcased by this [codepen](https://codepen.io/JacobStone/pen/GfLEn).
